CookieCutter conversion
ladybug-tools/ladybug-tools-template pull request #3
Opened 2019-07-26 09:50 UTC by AntoineDao

Here's a proposed change to the template repository setup so that it works with cookiecutter. The README.md at the root of the repo should be self-explanatory enough to enable pretty much anyone to generate their own ladybug-tools repo from scratch.

#4

2019-07-26 09:52 UTC, AntoineDao commented
Here is a quickstart to test this PR before merging it:

## QuickStart
1. Install [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/readme.html) and [pygithub](https://pygithub.readthedocs.io/en/latest/introduction.html) (to automate creating the repositories on Github after generating them locally)
```console
pip install cookiecutter pygithub
```
2. Run cookiecutter against this repository and follow the prompts
```console
cookiecutter gh:antoinedao/ladybug-tools-template

# Follow cookiecutter prompts
```

3. If you did not initialise the project on Github do so manually. Please visit https://github.com/new and create a repository for ladybug-tools/YOUR-PROJECT-SLUG (example: ladybug-tools/fire-ant for a project called Fire Ant). If you don't have the correct authorization to create repositories on the ladybug-tools organization then create a repo for your Github user and get in touch with the admins.

4. Activate the repository on [TravisCI](https://travis-ci.org/).
  
  ![image](https://user-images.githubusercontent.com/2915573/61428579-bbed0180-a8f0-11e9-8a4e-3ae7816c24a5.png)
  
  and set-up GH_TOKEN and PYPI_PASSWORD.

  ![image](https://user-images.githubusercontent.com/2915573/61428637-0c645f00-a8f1-11e9-9e5a-55b7a71536ed.png)

5. Activate this repository on [coveralls](https://coveralls.io/).

The repository should be ready! Now go write some actual code!

2019-08-07 16:20 UTC, mostaphaRoudsari approved these changes
Looks good! Thank you @AntoineDao. Let's make sure to remove `lbt-` from default package name before you merge this in.

It doesn't take advantage of GitHub template but it does everything that the template is supposed to do and does it even better.

I'm not sure how I feel about the auto deployment set-up right now. We probably should add github account / organization as one of the optional inputs instead of have it hard-coded to ladybug-tools [here](https://github.com/ladybug-tools/ladybug-tools-template/pull/3/files?file-filters%5B%5D=.cfg&file-filters%5B%5D=.md&file-filters%5B%5D=.py&file-filters%5B%5D=.rst&file-filters%5B%5D=.sh&file-filters%5B%5D=.txt&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile#diff-6936a93b31eaf599906bf674831050d3R54). In many cases even I do start the library on my personal account and then transfer it to Ladybug Tools. I can imagine other developers to use this repository to initiate a new library on their own repo and start the development and send a transfer request once it is ready to be added to ladybug-tools.

2019-08-07 16:20 UTC, mostaphaRoudsari commented on cookiecutter.json
> +  "pypi_name": "lbt-{{ cookiecutter.project_slug}}",
lbt should only be used for the libraries that packages different libraries together. I think we should remove it from the default name.

2019-08-07 16:20 UTC, mostaphaRoudsari commented on hooks/post_gen_project.py
> +import subprocess
This is cool and is basically what was behind the idea of using a repo as a template.  I think now that we are going to use cookicutter we should disable the template option.

2019-08-07 18:41 UTC, mostaphaRoudsari requested changes
There is a bug in `post_gen_project.py` which should be easy to fix.

Also let's make sure to remove `lbt-` from the default name.

2019-08-07 18:41 UTC, mostaphaRoudsari commented on hooks/post_gen_project.py
> +    pushed_to_github = push_to_github(git_initialised)
There is a bug here. push_to_github takes two inputs, you are passing only one.

```
  File "C:\Users\Mostapha\AppData\Local\Temp\tmprexzyd19.py", line 85, in <module>
    pushed_to_github = push_to_github(git_initialised)
TypeError: push_to_github() missing 1 required positional argument: 'git_initialised'
```

2019-08-07 21:09 UTC, mostaphaRoudsari commented
@AntoineDao, I tried it for `honeybee-radiance-command` repository and the new `.travis.yml` file was giving me errors for no good reason.

https://travis-ci.org/ladybug-tools/honeybee-radiance-command/builds/569051106

Changing it to the old one just worked fine

https://travis-ci.org/ladybug-tools/honeybee-radiance-command/builds/569057636

Otherwise it worked great and was such a joy to use.

2019-08-07 21:13 UTC, mostaphaRoudsari commented on {{cookiecutter.project_slug}}/README.md
> +## [API Documentation](http://ladybug-tools.github.io/apidoc/{{cookiecutter.project_slug}})
This is the wrong link.

```suggestion
## [API Documentation](http://ladybug-tools.github.io/{{cookiecutter.project_slug}}/docs)
```

2019-08-14 22:36 UTC, mostaphaRoudsari approved these changes
Looks great! Thanks. 🛫

2019-08-15 14:21 UTC, merged